---
title: "Hardness and forum"
output:
  html_document:
    code_download: yes
    fontsize: 8pt
    highlight: textmate
    number_sections: no
    theme: flatly
    toc: yes
    toc_float:
      collapsed: no
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(dplyr)
library(data.table)
library(lme4)
library(broom)
library(ggplot2)
library(tidyr)
library(arm)
library(car)
library(rstatix)
library(ggpubr)

remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}

```

```{r, include=FALSE}
wd <- getwd()

courses <- fread("../data/courses.csv") %>%
  mutate(visit_rate = round(vis_learner_b/ student_n, digits = 2), passing_rate = round(passing_rate, digits = 2)) 

students <- fread("../data/students.csv") %>%  mutate(duration = remove_outliers(duration))  
students$vis_b <- factor(students$vis_b)

assignments <- fread("unzip -cq ../data/assignments.zip")  %>%  
  mutate(course_item_type_desc = factor(course_item_type_desc), vis_b = ifelse(vis_tw==0, 0, 1)) %>% 
  group_by(course_item_id) %>% 
  mutate(difficulty =  sum(first_attempt == 0) / n()) %>% 
  ungroup() 
tw <- assignments %>% filter(assignment_time < 116) 
```

<!--

## 1. Влияние выживаемости на посещение форума

```{r}
m1 <-  lm(visit_rate ~ passing_rate, courses)
summary(m1)
```


## 2. Влияние длительности и выживаемости на посещение форума

```{r}
m1 <- glm(vis_b  ~ duration,  family = "binomial", students)
summary(m1)
m1 <- summary(m1)
cat(sprintf("Probability of attendance by increase of duration by 1 day is %.4f.\n", invlogit(m1$coefficients[2])))
```

-->

## 1. Влияние времени взаимодействия с заданием на посещение форума

```{r}
m1 <- glmer(vis_b ~ assignment_time + (1|course_item_name), family = "binomial", tw)
summary(m1)
m1 <- summary(m1)
cat(sprintf("Every additional minute of assignemnt interaction increase probability of attendance by %.2f.\n", invlogit(m1$coefficients[2])))
```


```{r, warning=FALSE}
assignments  %>%  ggplot(aes(x = assignment_time, y = vis_b)) +
  geom_point()   +  
# построит регрессионную линию, сигмоиду
  geom_smooth(method = "glm", method.args=list(family="binomial")) +   
# напечатает легенду, название графика и осей  
  ggtitle("Probability of forum attendance for\ndifferent duration of interaction with assignment") +
  labs(x = "Duration of interaction with assignment (in minutes)", y = "Forum attendance") +
# задает цветовую тему графика
  theme_bw() +  
# выравнивает название по центру
  theme(plot.title = element_text(hjust = 0.5))

```



## 2. Влияние числа попыток на посещение форума

```{r}
m1 <- glm(vis_b ~ attempts, family = "binomial", tw)
summary(m1)
m1 <- summary(m1)
cat(sprintf("Every additional attempt increase probability of attendance by %.4f.\n", invlogit(m1$coefficients[2])))
```

```{r, warning=FALSE}
tw  %>%  ggplot(aes(x = attempts, y = vis_b)) +
  geom_point()   +  
# построит регрессионную линию, сигмоиду
  geom_smooth(method = "glm", method.args=list(family="binomial")) +   
# напечатает легенду, название графика и осей  
  ggtitle("Probability of forum attendance\nfor different number of attempts") +
  labs(x = "Number of attempts", y = "Forum attendance") +
# задает цветовую тему графика
  theme_bw() +  
# выравнивает название по центру
  theme(plot.title = element_text(hjust = 0.5))

```

## 3. Влияние сложности на посещение форума

```{r}
m1 <- glm(vis_b ~ difficulty, family = "binomial", assignments)
summary(m1)
m1 <- summary(m1)
cat(sprintf("Every additional difficulty point increase probability of attendance by  %.4f.\n", invlogit(m1$coefficients[2])))
```

```{r, warning=FALSE}
assignments  %>%  ggplot(aes(x = difficulty, y = vis_b, color = vis_b)) +
  geom_point()   +  
# построит регрессионную линию, сигмоиду
  geom_smooth(method = "glm", method.args=list(family="binomial")) +   
# напечатает легенду, название графика и осей  
  ggtitle("Probability of forum attendance for different assignment difficulty") +
  labs(x = "Assignment difficulty", y = "Forum attendance", color = "Difficulty") +
# задает цветовую тему графика
  theme_bw() +  
# выравнивает название по центру
  theme(plot.title = element_text(hjust = 0.5))

```