---
title: "Plots"
output: html_document
date: "2022-10-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(dplyr)
library(data.table)
library(lme4)
library(ggplot2)
library(pscl) # for odTest
library(arm)
library(sjPlot)
library(rstatix)
library(car)
library(glue)
library(extrafont)

remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}

```

## Hypothesis 1

```{r}
h1 <- data.frame(vis_before_attempt_tw_b=c("No attendance","Attendance","Attendance","No attendance"), course_item_type_desc = c("quiz","programming","quiz","programming"),
                     results = c(0.7199075, 0.6692041, 0.6863616, 0.6823420))
colours = c("#599ad3", "#f9a65a", "#9e66ab")
ggplot(h1, aes(x = course_item_type_desc, y = results, fill = vis_before_attempt_tw_b)) + 
  geom_col(stat='identity', width = 0.6, position = position_dodge(0.7)) +
  geom_text(aes(label=round(results, digits =2)), vjust = 1.5, position=position_dodge(width=0.7), vjust=-0.25) +
  labs(x = "Type of an assignment", y = "Probability of Correctness on First Attempt", 
       fill="Forum attendance\nduring first attempt")+ 
  theme(
  axis.title.x = element_text(size=10),
  axis.title.y = element_text(size=10), 
       ) +
  scale_fill_manual(values=colours) + theme_classic()


```



